#!/usr/bin/env bash
# generate_strings.sh [<module>]
#
# Regenerates one module's bundle-aware L10n.swift from its Localizable.strings (§3.7).
# With no argument, regenerates every module listed in ios-skeleton.config.json (§3.7).
#
# Bundle strategy (§3.11 — never Bundle.main from inside a shared module):
#   - module directory contains Package.swift            -> Bundle.module
#   - otherwise (app target or framework project)         -> Bundle(for: a private token type)
#     which resolves to that module's own compiled bundle, not Bundle.main.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

generate_for_module_dir() {
  local module_dir="$1"
  local module_name
  module_name="$(basename "$module_dir")"

  local loc_dir=""
  if [ -d "$module_dir/Localization" ]; then
    loc_dir="$module_dir/Localization"
  elif [ -d "$module_dir/Resources/Localization" ]; then
    loc_dir="$module_dir/Resources/Localization"
  else
    echo "generate_strings.sh: no Localization/ under $module_dir — skipping."
    return 0
  fi

  local strings_file=""
  if [ -f "$loc_dir/en.lproj/Localizable.strings" ]; then
    strings_file="$loc_dir/en.lproj/Localizable.strings"
  elif [ -f "$loc_dir/Localizable.strings" ]; then
    strings_file="$loc_dir/Localizable.strings"
  else
    echo "generate_strings.sh: no base Localizable.strings under $loc_dir — skipping."
    return 0
  fi

  local bundle_strategy="token"
  if find "$module_dir" -maxdepth 2 -name "Package.swift" | grep -q .; then
    bundle_strategy="module"
  fi

  echo "generate_strings.sh: generating $loc_dir/L10n.swift for module '$module_name' (bundle: $bundle_strategy)"

  {
    echo "// Generated by Scripts/generate_strings.sh from Localizable.strings. Do not edit by hand."
    echo "// Regenerate with: Scripts/generate_strings.sh $module_name"
    echo "import Foundation"
    echo ""
    if [ "$bundle_strategy" = "token" ]; then
      echo "private final class L10nBundleToken {}"
      echo ""
      echo "private extension Bundle {"
      echo "    static let l10n = Bundle(for: L10nBundleToken.self)"
      echo "}"
    else
      echo "private extension Bundle {"
      echo "    static let l10n = Bundle.module"
      echo "}"
    fi
    echo ""
    echo "enum L10n {"
    echo "    fileprivate static func tr(_ key: String) -> String {"
    echo "        NSLocalizedString(key, bundle: .l10n, comment: \"\")"
    echo "    }"
    echo "}"
    echo ""

    awk '
      function swiftSafe(name) {
        gsub(/[^A-Za-z0-9_]/, "_", name)
        if (name ~ /^[0-9]/) { name = "_" name }
        reserved = " default class struct enum func var let if else for while return in import "
        if (index(reserved, " " name " ") > 0) { return "`" name "`" }
        return name
      }

      /^[[:space:]]*"([^"]+)"[[:space:]]*=/ {
        line = $0
        sub(/^[[:space:]]*"/, "", line)
        idx = index(line, "\"")
        key = substr(line, 1, idx - 1)
        n = split(key, parts, ".")

        parent = ""
        for (i = 1; i <= n; i++) {
          childpath = (parent == "" ? parts[i] : parent "." parts[i])
          if (!(parent SUBSEP parts[i] in seen)) {
            seen[parent SUBSEP parts[i]] = 1
            order[parent] = order[parent] " " parts[i]
          }
          parent = childpath
        }
        fullkey[parent] = key
        isLeaf[parent] = 1
      }

      function emit(path, indent,    i, n, names, name, childpath, pad) {
        pad = ""
        for (i = 0; i < indent; i++) pad = pad "    "
        n = split(order[path], names, " ")
        for (i = 1; i <= n; i++) {
          name = names[i]
          if (name == "") continue
          childpath = (path == "" ? name : path "." name)
          if (isLeaf[childpath] && !(childpath in order)) {
            printf "%sstatic var %s: String { L10n.tr(\"%s\") }\n", pad, swiftSafe(name), fullkey[childpath]
          } else {
            printf "%senum %s {\n", pad, swiftSafe(name)
            emit(childpath, indent + 1)
            printf "%s}\n", pad
          }
        }
      }

      END {
        printf "extension L10n {\n"
        emit("", 1)
        printf "}\n"
      }
    ' "$strings_file"
  } > "$loc_dir/L10n.swift"
}

resolve_module_dir() {
  # A module/app's folder name doesn't always match its config "name" (e.g. the
  # app target folder is conventionally "App" at T1/T2 regardless of the app's
  # real name — §3.1). Prefer the config's recorded path; fall back to searching
  # by literal directory name for the T2 Packages/<Name> convention.
  local name="$1"
  if [ -f ios-skeleton.config.json ] && command -v jq >/dev/null 2>&1; then
    local path
    path="$(jq -r --arg n "$name" '
      [((.apps // [])[] | select(.name == $n) | .path),
       ((.modules // [])[] | select(.name == $n) | .path)] | .[0] // ""
    ' ios-skeleton.config.json 2>/dev/null)"
    if [ -n "$path" ] && [ -d "$path" ]; then
      echo "$path"
      return 0
    fi
  fi
  for candidate in "Packages/$name" "$name"; do
    if [ -d "$candidate" ]; then
      echo "$candidate"
      return 0
    fi
  done
  find . -maxdepth 3 -type d -name "$name" -not -path "*/.build/*" | head -n1
}

if [ "$#" -ge 1 ]; then
  MODULE_DIR="$(resolve_module_dir "$1")"
  if [ -z "$MODULE_DIR" ]; then
    echo "generate_strings.sh: could not find module '$1'." >&2
    exit 1
  fi
  generate_for_module_dir "$MODULE_DIR"
else
  if [ ! -f ios-skeleton.config.json ]; then
    echo "generate_strings.sh: no module given and no ios-skeleton.config.json to enumerate modules from." >&2
    exit 1
  fi
  MODULE_NAMES="$(grep -oE '"name"[[:space:]]*:[[:space:]]*"[^"]+"' ios-skeleton.config.json | sed -E 's/.*"([^"]+)"$/\1/')"
  while IFS= read -r name; do
    [ -z "$name" ] && continue
    MODULE_DIR="$(resolve_module_dir "$name")"
    [ -n "$MODULE_DIR" ] && generate_for_module_dir "$MODULE_DIR"
  done <<< "$MODULE_NAMES"
fi
